/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appsukamaju;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author JON
 */
public class cOrderDetail extends javax.swing.JFrame {
 private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    /**
     * Creates new form cOrderDetail
     */
    public cOrderDetail() {
        initComponents();
        k.connect();
        refreshTable();
        refreshCombo();
    }
    
    class order_detail extends cOrderDetail{
        int idtransaksi, idmakanan, idminuman, harga, harga_minuman,jumlah_beli, total_bayar, pembayaran, kembalian, grand_total, pendapatan;
        String nama_pelanggan, tanggal, nama_makanan, nama_minuman;
        
        public order_detail(){
//            this.nama_pelanggan = txt_nama_pelanggan.getText();
//            String combo = combo_id_makanan.getSelectedItem().toString();
//            String[] arr = combo.split(":");
//            this.idmakanan = Integer.parseInt(arr[0]);
//            try {
//                Date date = txt_tanggal.getDate();
//                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
//                this.tanggal = dateformat.format(date);
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, e.getMessage());
//            }
//            this.nama_makanan = arr[1];
//            this.harga = Integer.parseInt(arr[2]);
//            this.jumlah_beli = Integer.parseInt(txt_jumlah_beli.getText());
//            this.total_bayar = this.harga * this.jumlah_beli;
//            this.pembayaran = Integer.parseInt(txt_pembayaran.getText());
//            this.kembalian = this.pembayaran - this.total_bayar;
//            this.pendapatan = Integer.parseInt(txt_pendapatan.getText());
            this.pendapatan = this.harga + this.harga;
//            this.pendapatan = Integer.parseInt(txt_pendapatan.getText());
            
        }
    }

    public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama Pelanggan");
        model.addColumn("ID Makanan");
        model.addColumn("Tanggal");
        model.addColumn("Nama Makanan");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Total Bayar");
        model.addColumn("Pembayaran");
        model.addColumn("Kembalian");
        tabel_order.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("select * from transaksi");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10)                   
                };
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    
    }
    
    public void refreshCombo(){
//        try {
//            this.stat = k.getCon().prepareStatement("select * from transaksi "
//                    + "where idtransaksi");
//            this.rs = this.stat.executeQuery();
//            while (rs.next()) {
//               combo_id_makanan.addItem(rs.getString("total_bayar")+":"+
//               rs.getString("nama_makanan")+":"+rs.getString("harga"));
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_order = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        combo_id_makanan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DETAIL ORDER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 990, -1));

        tabel_order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_orderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_order);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 990, 270));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Pendapatan : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        combo_id_makanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        combo_id_makanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "190.000" }));
        combo_id_makanan.setEnabled(false);
        combo_id_makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_id_makananActionPerformed(evt);
            }
        });
        getContentPane().add(combo_id_makanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 320, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabel_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_orderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_orderMouseClicked

    private void combo_id_makananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_id_makananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_id_makananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cOrderDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_id_makanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_order;
    // End of variables declaration//GEN-END:variables
}
