/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appsukamaju;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.view.JasperViewer;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author JON
 */
public class cTransaksi extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    /**
     * Creates new form cTransaksi
     */
    public cTransaksi() {
        initComponents();
        k.connect();
        refreshTable();
        refreshCombo();
    }
    
    class transaksi extends cTransaksi{
        int idtransaksi, idmakanan, idminuman, harga, harga_minuman,jumlah_beli, total_bayar, pembayaran, kembalian, grand_total;
        String nama_pelanggan, tanggal, nama_makanan, nama_minuman;
        
        public transaksi(){
            this.nama_pelanggan = txt_nama_pelanggan.getText();
            String combo = combo_id_makanan.getSelectedItem().toString();
            String[] arr = combo.split(":");
            this.idmakanan = Integer.parseInt(arr[0]);
            try {
                Date date = txt_tanggal.getDate();
                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
                this.tanggal = dateformat.format(date);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.nama_makanan = arr[1];
            this.harga = Integer.parseInt(arr[2]);
            this.jumlah_beli = Integer.parseInt(txt_jumlah_beli.getText());
            this.total_bayar = this.harga * this.jumlah_beli;
            this.pembayaran = Integer.parseInt(txt_pembayaran.getText());
            this.kembalian = this.pembayaran - this.total_bayar;
        }
    }
    
    public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama Pelanggan");
        model.addColumn("ID Makanan");
        model.addColumn("Tanggal");
        model.addColumn("Nama Makanan");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Total Bayar");
        model.addColumn("Pembayaran");
        model.addColumn("Kembalian");
        tabel_transaksi.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("select * from transaksi");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10)                   
                };
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txt_id_transaksi.setText("");
        txt_nama_pelanggan.setText("");
        txt_jumlah_beli.setText("");
        txt_total_bayar.setText("");
        txt_pembayaran.setText("");
    }
    
    
    public void refreshCombo(){
        try {
            this.stat = k.getCon().prepareStatement("select * from makanan "
                    + "where status='Tersedia'");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
               combo_id_makanan.addItem(rs.getString("idmakanan")+":"+
               rs.getString("nama_makanan")+":"+rs.getString("harga"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_pelanggan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nama_pelanggan = new javax.swing.JTextField();
        txt_id_transaksi = new javax.swing.JTextField();
        combo_id_makanan = new javax.swing.JComboBox<>();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_lihat_menu = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_cetak_laporan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_pembayaran = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_total_bayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_jumlah_beli = new javax.swing.JTextField();
        txt_kembalian = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        temp_laporan = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_tanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_transaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Makanan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 39, 370, 42));

        txt_pelanggan.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_pelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_pelanggan.setText("Pesanan : ");
        txt_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_pelangganMouseClicked(evt);
            }
        });
        getContentPane().add(txt_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Tanggal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Nama Pelanggan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 173, -1, -1));

        txt_nama_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_pelangganActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 166, 419, 38));

        txt_id_transaksi.setEnabled(false);
        txt_id_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 116, 419, 38));

        combo_id_makanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        combo_id_makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_id_makananActionPerformed(evt);
            }
        });
        getContentPane().add(combo_id_makanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 216, 320, 32));

        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        btn_ubah.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        btn_lihat_menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_lihat_menu.setText("Lihat Menu");
        btn_lihat_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lihat_menuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lihat_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, 30));

        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logout.setText("X");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, -1, -1));

        btn_cetak_laporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cetak_laporan.setText("Cetak Laporan");
        btn_cetak_laporan.setEnabled(false);
        getContentPane().add(btn_cetak_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Menu Makanan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 216, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Pembayaran");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        txt_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 140, 38));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Total Bayar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        txt_total_bayar.setEnabled(false);
        txt_total_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_bayarActionPerformed(evt);
            }
        });
        getContentPane().add(txt_total_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 150, 38));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Jumlah Beli");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        getContentPane().add(txt_jumlah_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 150, 38));

        txt_kembalian.setEnabled(false);
        getContentPane().add(txt_kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 140, 38));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Kembalian");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("ID Transaksi  ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 117, -1, -1));

        temp_laporan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        temp_laporan.setForeground(new java.awt.Color(255, 0, 0));
        temp_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temp_laporanMouseClicked(evt);
            }
        });
        getContentPane().add(temp_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 640, 170));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DETAIL TRANSAKSI");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 590, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Pesanan : ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 110, -1));
        getContentPane().add(txt_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 230, 30));

        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_transaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_transaksi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 640, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_pelangganMouseClicked

    }//GEN-LAST:event_txt_pelangganMouseClicked

    private void txt_id_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_transaksiActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        
         try {
            this.stat = k.getCon().prepareStatement("delete from transaksi where idtransaksi=?");
            stat.setInt(1, Integer.parseInt(txt_id_transaksi.getText()));
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        cLogin l = new cLogin();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_logoutActionPerformed

    
//    try {
//            makanan mkn = new makanan();
//            this.stat = k.getCon().prepareStatement("insert into makanan values(?,?,?,?)");
//            stat.setInt(1, 0);
//            stat.setString(2, mkn.nama_makanan);
//            stat.setInt(3, mkn.harga);
//            stat.setString(4, mkn.status);
//            stat.executeUpdate();
//            refreshTable();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//    }                                          
    
    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        try {
            transaksi tran = new transaksi();
            txt_total_bayar.setText(""+tran.total_bayar);
            this.stat = k.getCon().prepareStatement("insert into transaksi values(?,?,?,?,?,?,?,?,?,?)");
            this.stat.setInt(1, 0);
            this.stat.setString(2, tran.nama_pelanggan);
            this.stat.setInt(3, tran.idmakanan);
            this.stat.setString(4, tran.tanggal);
            this.stat.setString(5, tran.nama_makanan);
            this.stat.setInt(6, tran.harga);
            this.stat.setInt(7, tran.jumlah_beli);
            this.stat.setInt(8, tran.total_bayar);
            this.stat.setInt(9, tran.pembayaran);
            this.stat.setInt(10, tran.kembalian);
           
            int pilihan = JOptionPane.showConfirmDialog(null,
                    "Tanggal:"+tran.tanggal+
                    "\nNama Pelanggan: "+tran.nama_pelanggan+
                    "\nJumlah: "+tran.jumlah_beli+" "+tran.nama_makanan+
                    "\nTotal Bayar: "+tran.total_bayar+
                    "\nPembayaran: "+tran.pembayaran+
                    "\nKembalian: "+tran.kembalian+"\n",
                    "Tambahkan Transaksi?",
                    JOptionPane.YES_NO_OPTION);
            if (pilihan == JOptionPane.YES_OPTION) {
                this.stat.executeUpdate();
                refreshTable();
            } else if(pilihan == JOptionPane.NO_OPTION){
                refreshTable();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        
        
//         try {
//            user u = new user();
//            this.stat = k.getCon().prepareStatement("update user set username=?,"
//                + "password=?,nama_user=?,idlevel=? where iduser=?");
//            stat.setString(1, u.username);
//            stat.setString(2, u.password);
//            stat.setString(3, u.nama_user);
//            stat.setInt(4, u.idlevel);
//            stat.setString(5, txt_id_user.getText());
//            stat.executeUpdate(); // dari tabel gui ke mysql
//            refreshTable();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
        
        try {
            transaksi tran = new transaksi();
            tran.idtransaksi = Integer.parseInt(txt_id_transaksi.getText());
            this.stat = k.getCon().prepareStatement("update transaksi set nama_pelanggan=?,"
                    + "idmakanan=?,tanggal=?,nama_makanan=?,harga=?,jumlah_beli=?,total_bayar=?,pembayaran=?,kembalian=? "
                    + "where idtransaksi");
            this.stat.setString(1, tran.nama_pelanggan);
            this.stat.setInt(2, tran.idmakanan);
            this.stat.setString(3, tran.tanggal);
            this.stat.setString(4, tran.nama_makanan);
            this.stat.setInt(5, tran.harga);
            this.stat.setInt(6, tran.jumlah_beli);
            this.stat.setInt(7, tran.total_bayar);
            this.stat.setInt(8, tran.idtransaksi);
            this.stat.setInt(9, tran.pembayaran);
            this.stat.setInt(10, tran.kembalian);
            this.stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void temp_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temp_laporanMouseClicked
       
    }//GEN-LAST:event_temp_laporanMouseClicked

    private void combo_id_makananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_id_makananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_id_makananActionPerformed

    private void btn_lihat_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lihat_menuActionPerformed
        cMakanan mkn = new cMakanan();
        mkn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_lihat_menuActionPerformed

    private void txt_nama_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_pelangganActionPerformed

    private void tabel_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_transaksiMouseClicked
         txt_id_transaksi.setText(model.getValueAt(tabel_transaksi.getSelectedRow(),0).toString());
         txt_nama_pelanggan.setText(model.getValueAt(tabel_transaksi.getSelectedRow(),1).toString());
         txt_jumlah_beli.setText(model.getValueAt(tabel_transaksi.getSelectedRow(),6).toString());
         txt_total_bayar.setText(model.getValueAt(tabel_transaksi.getSelectedRow(),7).toString());
         txt_pembayaran.setText(model.getValueAt(tabel_transaksi.getSelectedRow(),8).toString());
         txt_kembalian.setText(model.getValueAt(tabel_transaksi.getSelectedRow(),9).toString());
         
    }//GEN-LAST:event_tabel_transaksiMouseClicked

    private void txt_total_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_bayarActionPerformed

    private void txt_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cetak_laporan;
    public javax.swing.JButton btn_hapus;
    public javax.swing.JButton btn_lihat_menu;
    public javax.swing.JButton btn_logout;
    public javax.swing.JButton btn_tambah;
    public javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox<String> combo_id_makanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel_transaksi;
    private javax.swing.JPanel temp_laporan;
    private javax.swing.JTextField txt_id_transaksi;
    private javax.swing.JTextField txt_jumlah_beli;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_nama_pelanggan;
    private javax.swing.JLabel txt_pelanggan;
    private javax.swing.JTextField txt_pembayaran;
    private com.toedter.calendar.JDateChooser txt_tanggal;
    private javax.swing.JTextField txt_total_bayar;
    // End of variables declaration//GEN-END:variables
}
